version: 2.1
jobs:
  bob:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  ibo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hello"
workflows:
  version: 2.1
  bob_ibo:
    jobs:
      - bob
      - ibo